### ISSUE TITLE
eff_map

### ISSUE THREAD

**Issue by ghost** [rc0r/afl-fuzz#3]
```
#define EFF_APOS(_p)          ((_p) >> EFF_MAP_SCALE2)
#define EFF_REM(_x)           ((_x) & ((1 << EFF_MAP_SCALE2) - 1))
#define EFF_ALEN(_l)          (EFF_APOS(_l) + !!EFF_REM(_l))
#define EFF_SPAN_ALEN(_p, _l) (EFF_APOS((_p) + (_l) - 1) - EFF_APOS(_p) + 1)

  /* Initialize effector map for the next step (see comments below). Always
     flag first and last byte as doing something. */

  eff_map    = ck_alloc(EFF_ALEN(len));
  eff_map[0] = 1;
```
The length of eff_map is 1/8 of  the length of the sample file, So it should be a bitmap, but it has only the value of 0 or 1 , why?

**Comment by rc0r** [comment]
This repo is just an unofficial git mirror of the afl-fuzz code. For questions regarding technical details please consider posting to the afl-users mailing list (https://groups.google.com/forum/#!forum/afl-users).

If you think there's a discrepancy between the official code tarballs and this repo, this is the right place to report to.
